(function (root) {
  'use strict';
  const MAX_TRAIL = 36;
  function appendBoundedTrail(trail, point, max = MAX_TRAIL) {
    const next = trail.concat([{ lat: point.lat, lng: point.lng }]);
    return next.slice(Math.max(0, next.length - max));
  }
  function localAsset(url) { return typeof url === 'string' && /^\/assets\/[a-z0-9._/-]+$/i.test(url); }
  function shader(gl, type, source) { const value=gl.createShader(type);gl.shaderSource(value,source);gl.compileShader(value);if(!gl.getShaderParameter(value,gl.COMPILE_STATUS))throw Error('WebGL shader compilation failed');return value; }
  function program(gl, vertex, fragment) { const value=gl.createProgram();gl.attachShader(value,shader(gl,gl.VERTEX_SHADER,vertex));gl.attachShader(value,shader(gl,gl.FRAGMENT_SHADER,fragment));gl.linkProgram(value);if(!gl.getProgramParameter(value,gl.LINK_STATUS))throw Error('WebGL program link failed');return value; }
  function geometry(segments=64,rings=32){const vertices=[],indices=[];for(let y=0;y<=rings;y++){const lat=(y/rings-.5)*Math.PI;for(let x=0;x<=segments;x++){const lon=(x/segments-.5)*Math.PI*2;vertices.push(Math.cos(lat)*Math.sin(lon),Math.sin(lat),Math.cos(lat)*Math.cos(lon),x/segments,1-y/rings)}}for(let y=0;y<rings;y++)for(let x=0;x<segments;x++){const a=y*(segments+1)+x,b=a+segments+1;indices.push(a,b,a+1,b,b+1,a+1)}return {vertices:new Float32Array(vertices),indices:new Uint16Array(indices)};}
  function createGlobe({canvas,overlay,interaction=canvas,container,marker,fallback,textureUrl='/assets/earth-texture.svg',reducedMotion=false}) {
    if (!canvas || !localAsset(textureUrl)) throw Error('A local Earth texture is required');
    const gl=canvas.getContext('webgl',{alpha:true,antialias:true,powerPreference:'low-power'});
    if(!gl) throw Error('WebGL is unavailable');
    const vs='attribute vec3 p;attribute vec2 uv;uniform float yaw;uniform float pitch;uniform float aspect;uniform float scale;varying vec2 vuv;varying vec3 normal;void main(){mat3 ry=mat3(cos(yaw),0.,-sin(yaw),0.,1.,0.,sin(yaw),0.,cos(yaw));mat3 rx=mat3(1.,0.,0.,0.,cos(pitch),sin(pitch),0.,-sin(pitch),cos(pitch));vec3 q=rx*ry*p;normal=q;gl_Position=vec4(q.x*scale/aspect,q.y*scale,q.z*.2,1.);vuv=uv;}';
    const fs='precision mediump float;varying vec2 vuv;varying vec3 normal;uniform sampler2D earth;void main(){vec3 light=normalize(vec3(-.45,.7,.8));float d=max(dot(normalize(normal),light),0.);float rim=pow(1.-max(normal.z,0.),3.);vec3 tex=texture2D(earth,vuv).rgb;vec3 color=tex*(.28+.82*d)+vec3(.08,.32,.5)*rim*.45;gl_FragColor=vec4(color,1.);}';
    const prog=program(gl,vs,fs),geo=geometry();gl.useProgram(prog);
    const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,geo.vertices,gl.STATIC_DRAW);const stride=20;for(const [name,size,offset] of [['p',3,0],['uv',2,12]]){const loc=gl.getAttribLocation(prog,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,stride,offset)}const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,geo.indices,gl.STATIC_DRAW);
    const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([11,55,91,255]));
    let yaw=0,pitch=.12,scale=.84,trail=[],state=null,drag=false,px=0,py=0,raf=0,visible=!document.hidden,destroyed=false;
    const image=new Image();image.onload=()=>{gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,image);gl.generateMipmap(gl.TEXTURE_2D);container.classList.add('webgl-ready');fallback.hidden=true;render();};image.onerror=()=>fail('Earth texture could not be loaded');image.src=textureUrl;
    const ctx=overlay.getContext('2d');
    function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);for(const c of [canvas,overlay]){c.width=Math.max(1,Math.floor(rect.width*dpr));c.height=Math.max(1,Math.floor(rect.height*dpr))}gl.viewport(0,0,canvas.width,canvas.height);render();}
    function rotate(point){const a=(point.lng*Math.PI/180)+yaw,b=point.lat*Math.PI/180;let x=Math.cos(b)*Math.sin(a),y=Math.sin(b),z=Math.cos(b)*Math.cos(a);const y2=y*Math.cos(pitch)+z*Math.sin(pitch),z2=-y*Math.sin(pitch)+z*Math.cos(pitch);return {x,y:y2,z:z2};}
    function position(point){const q=rotate(point),rect=canvas.getBoundingClientRect(),radius=Math.min(rect.width,rect.height)*scale/2;return {x:rect.width/2+q.x*radius,y:rect.height/2-q.y*radius,visible:q.z>0};}
    function overlayDraw(){const rect=overlay.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);const points=trail.map(position).filter(p=>p.visible);if(points.length>1){ctx.strokeStyle='rgba(85,229,240,.68)';ctx.lineWidth=1.5;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}if(state){const p=position(state);marker.hidden=!p.visible;marker.style.left=`${p.x}px`;marker.style.top=`${p.y}px`;marker.setAttribute('aria-label',`ISS at ${state.lat.toFixed(2)} degrees latitude and ${state.lng.toFixed(2)} degrees longitude`);}}
    function render(){if(destroyed||!visible)return;cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>{const rect=canvas.getBoundingClientRect();gl.useProgram(prog);gl.uniform1f(gl.getUniformLocation(prog,'yaw'),yaw);gl.uniform1f(gl.getUniformLocation(prog,'pitch'),pitch);gl.uniform1f(gl.getUniformLocation(prog,'aspect'),rect.width/Math.max(rect.height,1));gl.uniform1f(gl.getUniformLocation(prog,'scale'),scale);gl.enable(gl.DEPTH_TEST);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.drawElements(gl.TRIANGLES,geo.indices.length,gl.UNSIGNED_SHORT,0);overlayDraw();});}
    function fail(){container.classList.remove('webgl-ready');fallback.hidden=false;marker.hidden=true;}
    function down(e){drag=true;px=e.clientX;py=e.clientY;interaction.setPointerCapture(e.pointerId)}function move(e){if(!drag)return;yaw+=(e.clientX-px)*.008;pitch=Math.max(-.8,Math.min(.8,pitch+(e.clientY-py)*.006));px=e.clientX;py=e.clientY;render()}function up(){drag=false}function wheel(e){e.preventDefault();scale=Math.max(.58,Math.min(1.05,scale-e.deltaY*.0007));render()}function key(e){const keys={ArrowLeft:[-.08,0],ArrowRight:[.08,0],ArrowUp:[0,-.06],ArrowDown:[0,.06]};if(keys[e.key]){e.preventDefault();yaw+=keys[e.key][0];pitch=Math.max(-.8,Math.min(.8,pitch+keys[e.key][1]));render()}}
    interaction.addEventListener('pointerdown',down);interaction.addEventListener('pointermove',move);interaction.addEventListener('pointerup',up);interaction.addEventListener('wheel',wheel,{passive:false});interaction.addEventListener('keydown',key);const observer=new ResizeObserver(resize);observer.observe(container);const visibility=()=>{visible=!document.hidden;if(visible)render();};document.addEventListener('visibilitychange',visibility);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fail();});
    resize();if(!reducedMotion)render();
    return {setTelemetry(value){state={lat:value.latitude,lng:value.longitude};trail=appendBoundedTrail(trail,state);render();},getTrail:()=>trail.slice(),destroy(){destroyed=true;cancelAnimationFrame(raf);observer.disconnect();document.removeEventListener('visibilitychange',visibility);},render};
  }
  const api={createGlobe,appendBoundedTrail,localAsset,MAX_TRAIL};if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root)root.MissionGlobe=api;
})(typeof window==='undefined'?null:window);
